<a href="https://colab.research.google.com/github/Daksh-Mistry/Heart-Failure-Prediction/blob/main/Heart_Failure_Prediction_Using_Logistic_Regession.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Heart Failure Prediction Using Logistic Regession

In [ ]:
!wget -q https://www.kaggle.com/api/v1/datasets/download/fedesoriano/heart-failure-prediction

In [ ]:
!unzip -q '/content/heart-failure-prediction'

In [159]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [160]:
df = pd.read_csv('/content/heart.csv')
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [161]:
df['RestingECG'].value_counts()

RestingECG
Normal    552
LVH       188
ST        178
Name: count, dtype: int64

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [163]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [164]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['ChestPainType_Encoded'] = encoder.fit_transform(df['ChestPainType'])

In [165]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['ExerciseAngina_Encoded'] = encoder.fit_transform(df['ExerciseAngina'])

In [166]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Sex_Encoded'] = encoder.fit_transform(df['Sex'])

In [167]:
df.drop(columns=['ChestPainType','Sex','ExerciseAngina'], inplace = True)

In [168]:
df.head()

,Age,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,Oldpeak,ST_Slope,HeartDisease,ChestPainType_Encoded,ExerciseAngina_Encoded,Sex_Encoded
0,40,140,289,0,Normal,172,0.0,Up,0,1,0,1
1,49,160,180,0,Normal,156,1.0,Flat,1,2,0,0
2,37,130,283,0,ST,98,0.0,Up,0,1,0,1
3,48,138,214,0,Normal,108,1.5,Flat,1,0,1,0
4,54,150,195,0,Normal,122,0.0,Up,0,2,0,1

In [151]:
# df.drop( columns = ['Sex_Encoded','FastingBS','ST_Slope', 'Oldpeak'], inplace =True)

In [172]:
df_final = pd.get_dummies(df, columns=['RestingECG','ST_Slope'], dtype=int)

df_final.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,ChestPainType_Encoded,ExerciseAngina_Encoded,Sex_Encoded,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,0,1,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,2,0,0,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,0,1,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,1,0,0,1,0,0,1,0
4,54,150,195,0,122,0.0,0,2,0,1,0,1,0,0,0,1

In [173]:
from sklearn.model_selection import train_test_split
y = df_final['HeartDisease']
df_final.drop(columns=['HeartDisease'], inplace = True)
X = df_final
X_train, X_test ,y_train ,y_test = train_test_split(X,y, test_size = 0.20, random_state=20)

In [174]:
X_train.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,ChestPainType_Encoded,ExerciseAngina_Encoded,Sex_Encoded,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
175,43,140,288,0,135,2.0,0,1,1,0,1,0,0,1,0
503,51,132,227,1,138,0.2,0,0,1,0,0,1,0,0,1
89,55,140,229,0,110,0.5,0,1,1,0,1,0,0,1,0
261,54,120,221,0,138,1.0,1,0,0,0,1,0,0,0,1
213,56,130,219,0,164,0.0,2,0,0,0,0,1,0,0,1

In [175]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train[['Age','RestingBP','Cholesterol','MaxHR','Oldpeak']] = scaler.fit_transform(X_train[['Age','RestingBP','Cholesterol','MaxHR','Oldpeak']])
X_test[['Age','RestingBP','Cholesterol','MaxHR','Oldpeak']] = scaler.transform(X_test[['Age','RestingBP','Cholesterol','MaxHR','Oldpeak']])

In [176]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [177]:
pred = model.predict(X_test)

In [178]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, pred))
print(confusion_matrix(y_test, pred))

0.8641304347826086
[[71 14]
 [11 88]]